name: Sync to Forked Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "MyungJiwoo"
          git config user.email "1206jiwoo@gmail.com"

      - name: Add fork remote and push current branch
        run: |
          git remote add forked-repo https://MyungJiwoo:${{ secrets.AUTO_ACTIONS }}@github.com/MyungJiwoo/What-Today.git
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Pushing branch: $CURRENT_BRANCH"
          git push -f forked-repo $CURRENT_BRANCH

      - name: Clean up
        run: git remote remove forked-repo
