name: Deploy to Vercel (Monorepo)

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'
      - '.eslintrc.*'
      - '.prettierrc*'
      - '*.md'

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://MyungJiwoo:${{ secrets.AUTO_ACTIONS }}@github.com/MyungJiwoo/What-Today
          git config user.name MyungJiwoo
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
